apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trailox-agent.fullname" . }}-config
  labels:
    {{- include "trailox-agent.labels" . | nindent 4 }}
data:
  agent.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
